@startuml
!include theme.ipuml
start

:Initialize LoopManager;
:Start LoopTimer;

repeat
	:Update LoopTimer;
	:Check for Events;
	:Process Input;

	while (Lag >= Fixed Delta Time?) is (yes)
		:Perform Fixed Update;
		:Advance Fixed Update;
	endwhile

	:Perform Normal Update;
	:Render Frame;

repeat while (Game Running?)

:Game exit logic;

stop
@enduml
